name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
      env:
        CI: true
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Restore tools
      run: dotnet tool restore
    - name: Install JS dependencies
      run: npm install
    - name: Build client-side code
      run: dotnet fable src/Client --run parcel build index.html
    - name: Build server
      run: dotnet build src/Server/Server.fsproj -c Release